@startuml
skinparam classAttributeIconSize 0
skinparam linetype ortho
top to bottom direction


'Declaring things
database "Google DB" as db

package "Cilent" as Cilent{
  package  "Presentation Layer"  as Presentation{
    [Change Password View] as PasswordView
    [Admin View] as AdminView
    [Staff View] as StaffView
    [Manager View] as ManagerView

  }
}

package "Server" as server{
  package  "Business Layer" as Business {
    [Admin ] as Admin
    [Staff ] as Staff
    [Manager ] as Manager
    [Job ] as Job
    [Inventory] as Inventory
    [Password] as Password

  }

  package "Persistent Layer" as Persistent {
    [User DAO] as UserDAO
    [Job DAO] as JobDAO
    [Password DAO] as PasswordDAO
    [Inventory DAO] as InventoryDAO
    [Staff Availability DAO] as StaffAvailabilityDAO

  }

}

cloud "Restful API" as RestfulAPI{
}


Presentation <-r-> RestfulAPI
RestfulAPI <-l->  Business
Business <--->  Persistent

Persistent <-> db


'Google -- OTP
'Password --( OTP

@enduml