@startuml

class User as "<<entity>>\nUser"{
 -name:String
 -email:String
 -maskedNRIC:String
 -jobTitle:String
 -phone_Number:String
 -starting_Date:String
 +getName():String
 +setName():Void
 +getEmail():String
 +setEmail():Void
 +getMaskedNRIC():String
+setMaskedNRIC():Void
 +getJobTitle():String
 +setJobTitle():Void
 +getPhone_Number():String
 +setPhone_Number():Void
 +getStarting_Date():String
 +setStarting_Date():Void
}

class Staff as "<<entity>>\nStaff"{
 -staffID:Integer
 +getStaffID():Integer
 +setStaffID():Void
 -qualification:ArrayList<String>
 +getQualification():ArrayList<String>
 +setQualification():Void
}

class Admin as "<<entity>>\nAdmin"{
 -adminID:Integer
 +getAdminID():Integer
 +setAdminID():Void
}

class Manager as "<<entity>>\nManager"{
 -managerID:Integer
 +getManagerID():Integer
 +setManagerID():Void
}

class Job as "<<entity>>\nJob" {
 -jobID:Integer
 -getDate:Date
 -getTime:Time
 +getJobID():Integer
 +setJobID():Void
 +getGetDate():Date
 +setGetDate():Void
 +getGetTime():Time
 +setGetTime():Void

}

class JobAssignments as "<<entity>>\nJobAssignments"
{
   -AssignedStaff:ArrayList<User>
   -Preferences:ArrayList<User>
   +getSetAssignedStaff():ArrayList<User>
   +setAssignedStaff():Void
   +getPerferences():ArrayList<User>
   +setPerferences():Void
}
class Password as "<<Entity>>\nPassword"{
  -EncrpytedPassword:String
  +getEncrpyted_Password():String
  +setEncrpyted_Password():Voids
}
class StaffAvailability as "<<Entity>>\nPassword"{
  -EncrpytedPassword:String
  +getEncrpyted_Password():String
  +setEncrpyted_Password():Voids
}

'Controller' class
class AdminController as "<<Control>>\nAdminController"{
 +editUser():Void
 +addUser():Void
 +deleteUser():Void
 +viewAllStaff():Void
}


' Inheritance
User <|-- Staff
User <|-- Manager
User <|-- Admin

'Aggregation
JobAssignments -- Manager : Assigns
JobAssignments o-- Staff : Show perference

' Composite
User *-l- Password
Job *-- JobAssignments

@enduml