@startuml
top to bottom direction

'Interface

'Declaring things
database "Google DB" as db
[Google Oauth] as Google #Pink

package "Cilent" as Cilent{
  package  "Presentation Layer"  as Presentation{
    [Change Password View] as PasswordView
    [Admin View] as AdminView
    [Staff View] as StaffView
    [Manager View] as ManagerView

  }
}

package "Server" as server{
  Interface "Access User DB" as EditUser
  Interface "Access Job DB" as UpdateJob
  Interface "Update Password" as UpdatePassword
  Interface "Access Inventory DB" as UpdateInventory
  Interface "Access Availibility DB" as UpdateStaffAvailabliy

  package  "Business Layer" as Business {
    [Admin ] as Admin
    [Staff ] as Staff
    [Manager ] as Manager
    [Job ] as Job
    [Inventory] as Inventory
    [Password] as Password
    Admin -d-( EditUser
    Staff -d-( EditUser
    Manager -d-( EditUser
    Staff -d-( UpdateStaffAvailabliy
    Manager -d-( UpdateStaffAvailabliy
    Job -d-( UpdateJob
    Inventory -d-( UpdateInventory
    Password -d-( UpdatePassword


  }

  package "Persistent Layer" as Persistent {
    [User DAO] as UserDAO
    [Job DAO] as JobDAO
    [Password DAO] as PasswordDAO
    [Inventory DAO] as InventoryDAO
    [Staff Availability DAO] as StaffAvailabilityDAO
    UserDAO -u- EditUser
    JobDAO -u- UpdateJob
    PasswordDAO -u- UpdatePassword
    InventoryDAO -u- UpdateInventory
    StaffAvailabilityDAO -u- UpdateStaffAvailabliy
  }

}

cloud "Restful API" as RestfulAPI{
}
' Business <-d->  Persistent

' Persistent <-> db


Interface "Generate OTP" as OTP
Interface "Request" as HTTPRequest
Interface "Response" as HTTPResponse
Interface "Access Google Database" as AccessDB

RestfulAPI -d- HTTPResponse
RestfulAPI -u- HTTPRequest

PasswordView -d-( HTTPRequest
StaffView -d-( HTTPRequest
AdminView -d-( HTTPRequest
ManagerView -d-( HTTPRequest


Admin  -u-( HTTPResponse
Staff -u-( HTTPResponse
Manager -u-( HTTPResponse
Job -u-( HTTPResponse
Inventory -u-( HTTPResponse
Password -u-( HTTPResponse

Password -u-( OTP
Google -( OTP


UserDAO -d-( AccessDB
JobDAO -d-( AccessDB
PasswordDAO -d-( AccessDB
InventoryDAO -d-( AccessDB
StaffAvailabilityDAO -d-( AccessDB

db -u- AccessDB


@enduml