@startuml
top to bottom direction

'Interface

'Declaring things
database "Google DB" as db
[Google Oauth] as Google #Pink

package "Cilent" as Cilent{
  
  package  "Presentation Layer"  as Presentation{
    Interface "Basic UI" as UserInterface
    Interface "Password UI" as PasswordUI
    Interface "Admin UI" as AdminUI
    Interface "Staff UI" as StaffUI
    Interface "Manager UI" as ManagerUI
    Interface "Login UI" as LoginUI

    [Base View] as BasicView
    [Login View] as LoginView
    [Change Password View] as PasswordView
    [Admin View] as AdminView
    [Staff View] as StaffView
    [Manager View] as ManagerView

    AdminView -u- AdminUI
    PasswordView -u- PasswordUI
    StaffView -u- StaffUI
    ManagerView -u- ManagerUI
    LoginView -u- LoginUI

    BasicView -d-( AdminUI
    BasicView -d-( PasswordUI
    BasicView -d-( StaffUI
    BasicView -d-( ManagerUI
    BasicView -d-( LoginUI
    BasicView -u- UserInterface


  }
}

package "Server" as server{
  Interface "IDAO" as accessDAO 

  package  "Business Layer" as Business {
    [AccountController ] as Admin
    [LoginController ] as Staff
    [ScheduleManager ] as Manager
    [JobManagement ] as Job
    [VanController] as Van
    [PasswordController] as Password
    Admin -d-( accessDAO
    Staff -d-( accessDAO
    Manager -d-( accessDAO
    Job -d-( accessDAO
    Van -d-( accessDAO
    Password -d-( accessDAO


  }

  package "Persistent Layer" as Persistent {
    [User DAO] as UserDAO
    [Job DAO] as JobDAO
    [Password DAO] as PasswordDAO
    [Van DAO] as VanDAO
    [Staff Availability DAO] as StaffAvailabilityDAO
    UserDAO -u- accessDAO
    JobDAO -u- accessDAO
    PasswordDAO -u- accessDAO
    VanDAO -u- accessDAO
    StaffAvailabilityDAO -u- accessDAO
  }

}

cloud "Restful API" as RestfulAPI{
}
' Business <-d->  Persistent

' Persistent <-> db


Interface "Generate OTP" as OTP
Interface "Request" as HTTPRequest
Interface "Access Google Database" as AccessDB

RestfulAPI -u- HTTPRequest
PasswordView --d-( HTTPRequest
StaffView -d-( HTTPRequest
AdminView -d-( HTTPRequest
ManagerView -d-( HTTPRequest
LoginView -d-( HTTPRequest

Interface "IScheduleManager" as IManager
Interface "ILoginController" as IStaff
Interface "IAccountController" as IAdmin
Interface "IJobManagement" as IJob
Interface "IPasswordController" as IPassword
Interface "IVanController" as IVan

Admin  -u- IAdmin
Staff -u- IStaff
Manager -u- IManager
Job -u- IJob
Van -u- IVan
Password -u- IPassword

RestfulAPI  -d-( IAdmin
RestfulAPI -d-( IStaff
RestfulAPI -d-( IManager
RestfulAPI -d-( IJob
RestfulAPI -d-( IVan
RestfulAPI -d-( IPassword


Password -d-( OTP
Google -u- OTP


UserDAO -d-( AccessDB
JobDAO -d-( AccessDB
PasswordDAO -d-( AccessDB
VanDAO -d-( AccessDB
StaffAvailabilityDAO -d-( AccessDB

db -u- AccessDB


@enduml