@startuml
skinparam classAttributeIconSize 0
skinparam linetype ortho
top to bottom direction

'Interface

'Declaring things
database "Google DB" as db
[Google Oauth] as Google #Pink

package "Cilent" as Cilent{
  package  "Presentation Layer"  as Presentation{
    [Change Password View] as PasswordView
    [Admin View] as AdminView
    [Staff View] as StaffView
    [Manager View] as ManagerView

  }
}

package "Server" as server{
  Interface "Edit User" as EditUser
  Interface "Update Job" as UpdateJob
  Interface "Update Password" as UpdatePassword
  Interface "Update Inventory" as UpdateInventory
  Interface "Update StaffAvailabliy" as UpdateStaffAvailabliy

  package  "Business Layer" as Business {
    [Admin ] as Admin
    [Staff ] as Staff
    [Manager ] as Manager
    [Job ] as Job
    [Inventory] as Inventory
    [Password] as Password

  }

  package "Persistent Layer" as Persistent {
    [User DAO] as UserDAO
    [Job DAO] as JobDAO
    [Password DAO] as PasswordDAO
    [Inventory DAO] as InventoryDAO
    [Staff Availability DAO] as StaffAvailabilityDAO
    UserDAO -u- EditUser
    JobDAO -u- UpdateJob
    PasswordDAO -u- UpdatePassword
    InventoryDAO -u- UpdateInventory
    StaffAvailabilityDAO -u- UpdateStaffAvailabliy
  }

}

cloud "Restful API" as RestfulAPI{
}
Business <--->  Persistent

Persistent <-> db


Interface "Request OTP" as OTP
Interface "Request" as HTTPRequest
Interface "Response" as HTTPResponse


RestfulAPI -l- HTTPResponse
RestfulAPI -r- HTTPRequest

PasswordView -( HTTPRequest
StaffView -( HTTPRequest
AdminView -( HTTPRequest
ManagerView -( HTTPRequest


Admin  --( HTTPResponse
Staff --( HTTPResponse
Manager --( HTTPResponse
Job --( HTTPResponse
Inventory --( HTTPResponse
Password --( HTTPResponse







@enduml